name: goals-server-ts

services:
  pg: 
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rafaella.lopes
      - POSTGRES_PASSWORD=goals
      - POSTGRES_DB=goals